# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  iconFontBuilder:
    import: "package:flutter_app_demo/builder/iconfont_builder.dart"
    builder_factories: ["iconFontBuilder"]
    build_extensions:
      { "assets/fonts/iconfont.json": ["lib/gen/icon_font.gen.dart"] }
    build_to: source
    auto_apply: root_package
