name: flutter_app_demo
description: "A new Flutter project template."

# 防止项目被意外发布到 `pub.dev`
publish_to: "none"

# 版本号格式：major.minor.patch+build_number
version: 1.0.0+1

# 指定 Dart SDK 版本
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # 提供 iOS 风格的图标 (Cupertino Icons)
  cupertino_icons: ^1.0.8

  # 状态管理
  get: ^4.7.2

  # JSON 序列化注解库，配合 `json_serializable` 自动生成 JSON 解析代码
  json_annotation: ^4.9.0

dev_dependencies:
  # Flutter 官方测试框架，支持 Widget 测试、单元测试、集成测试等
  flutter_test:
    sdk: flutter

  # 代码生成工具，负责执行 `build.yaml` 规则
  # 用于自动生成 Dart 代码，例如 JSON 序列化、依赖注入等
  build_runner: ^2.4.14

  # Dart 构建工具，配合 `build_runner` 进行代码生成
  build: ^2.4.2

  # 用于生成 Flutter 代码，如 `Assets`、`Strings`、`Colors` 等
  flutter_gen_runner: ^5.10.0

  # JSON 序列化代码生成工具，基于 `json_annotation`
  # 通过 `build_runner` 自动生成 `*.g.dart` 文件
  json_serializable: ^6.9.4

  # Flutter 官方推荐的代码规范检查工具，提供一系列 Lint 规则
  flutter_lints: ^5.0.0

  # 这里是资源生成配置
flutter_gen:
  # Optional (default: lib/gen/)
  output: lib/gen/
  # Optional (default: 80)
  line_length: 80
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
  fonts:
    enabled: false

flutter:
  # 确保 Material Icons 可用
  uses-material-design: true

  # 静态资源配置
  assets:
    - assets/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  # 自定义字体配置
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
# 依赖覆盖（如果需要固定某些库版本）
# dependency_overrides:
#   some_package: 1.2.3
